/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

import java.util.List;
import java.util.Map;
import javax.swing.DefaultListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author akamojo
 */
public class CustomerDialog extends javax.swing.JDialog {

    private List<Klient> listaKlientow;
    private Restauracja restauracja;
    private Map<Integer, Klient> mapaKlientow;

    /**
     * Creates new form CustomerDialog
     *
     * @param parent
     * @param modal
     */
    public CustomerDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolbarPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        customerTableScrollPane = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        customerPanel = new javax.swing.JPanel();
        typeComboBox = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        telephoneLabel = new javax.swing.JLabel();
        telephoneTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        adressPanel = new javax.swing.JPanel();
        streetLabel = new javax.swing.JLabel();
        streetTextField = new javax.swing.JTextField();
        nrLabel = new javax.swing.JLabel();
        nrTextField = new javax.swing.JTextField();
        xLabel = new javax.swing.JLabel();
        xTextField = new javax.swing.JTextField();
        yLabel = new javax.swing.JLabel();
        yTextField = new javax.swing.JTextField();
        specialPanel = new javax.swing.JPanel();
        codeLabel = new javax.swing.JLabel();
        codeTextField = new javax.swing.JTextField();
        discountLabel = new javax.swing.JLabel();
        discountTextField = new javax.swing.JTextField();
        pointsLabel = new javax.swing.JLabel();
        pointsTextField = new javax.swing.JTextField();
        accountNumberLabel = new javax.swing.JLabel();
        accountNumberTextField = new javax.swing.JTextField();
        regonLabel = new javax.swing.JLabel();
        regonTextField = new javax.swing.JTextField();
        companyAdressPanel = new javax.swing.JPanel();
        cStreetLabel = new javax.swing.JLabel();
        cStreetTextField = new javax.swing.JTextField();
        cNrLabel = new javax.swing.JLabel();
        cNrTextField = new javax.swing.JTextField();
        cXLabel = new javax.swing.JLabel();
        cXTextField = new javax.swing.JTextField();
        cYLabel = new javax.swing.JLabel();
        cYTextField = new javax.swing.JTextField();
        orderPanel = new javax.swing.JPanel();
        addOrderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Klienci");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(300, 500));
        setPreferredSize(new java.awt.Dimension(600, 800));

        toolbarPanel.setLayout(new java.awt.GridBagLayout());

        addButton.setText("Dodaj Klienta");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolbarPanel.add(addButton, gridBagConstraints);

        removeButton.setText("Usuń Klienta");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolbarPanel.add(removeButton, gridBagConstraints);

        changeButton.setText("Zmień Klienta");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolbarPanel.add(changeButton, gridBagConstraints);

        getContentPane().add(toolbarPanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.setLayout(new java.awt.GridBagLayout());

        tablePanel.setLayout(new java.awt.GridBagLayout());

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Imię", "Nazwisko", "Rodzaj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        customerTable.setSelectionModel(new DefaultListSelectionModel() {
            public void selectionChanged(ListSelectionEvent e) {
                if(e.getValueIsAdjusting()) {

                }
            }
        });
        customerTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        customerTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    selectCustomer();
                }
            }
        });
        customerTableScrollPane.setViewportView(customerTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        tablePanel.add(customerTableScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(tablePanel, gridBagConstraints);

        customerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Klient"));
        customerPanel.setLayout(new java.awt.GridBagLayout());

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Okazjonalny", "Stały", "Firmowy" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        customerPanel.add(typeComboBox, gridBagConstraints);

        typeLabel.setText("Rodzaj Klienta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        customerPanel.add(typeLabel, gridBagConstraints);

        firstNameLabel.setText("Imię");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        customerPanel.add(firstNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        customerPanel.add(firstNameTextField, gridBagConstraints);

        nameLabel.setText("Nazwisko");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        customerPanel.add(nameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        customerPanel.add(nameTextField, gridBagConstraints);

        telephoneLabel.setText("Numer telefonu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        customerPanel.add(telephoneLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        customerPanel.add(telephoneTextField, gridBagConstraints);

        emailLabel.setText("E-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        customerPanel.add(emailLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        customerPanel.add(emailTextField, gridBagConstraints);

        adressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Adres"));
        adressPanel.setLayout(new java.awt.GridBagLayout());

        streetLabel.setText("Ulica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        adressPanel.add(streetLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        adressPanel.add(streetTextField, gridBagConstraints);

        nrLabel.setText("Numer domu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        adressPanel.add(nrLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        adressPanel.add(nrTextField, gridBagConstraints);

        xLabel.setText("Położenie X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        adressPanel.add(xLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        adressPanel.add(xTextField, gridBagConstraints);

        yLabel.setText("Położenie Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        adressPanel.add(yLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        adressPanel.add(yTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        customerPanel.add(adressPanel, gridBagConstraints);

        specialPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        specialPanel.setLayout(new java.awt.GridBagLayout());

        codeLabel.setText("Kod");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        specialPanel.add(codeLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        specialPanel.add(codeTextField, gridBagConstraints);

        discountLabel.setText("Zniżka");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        specialPanel.add(discountLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        specialPanel.add(discountTextField, gridBagConstraints);

        pointsLabel.setText("Punkty lojalnościowe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        specialPanel.add(pointsLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        specialPanel.add(pointsTextField, gridBagConstraints);

        accountNumberLabel.setText("Numer konta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        specialPanel.add(accountNumberLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        specialPanel.add(accountNumberTextField, gridBagConstraints);

        regonLabel.setText("REGON");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        specialPanel.add(regonLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        specialPanel.add(regonTextField, gridBagConstraints);

        companyAdressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Adres"));
        companyAdressPanel.setLayout(new java.awt.GridBagLayout());

        cStreetLabel.setText("Ulica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        companyAdressPanel.add(cStreetLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        companyAdressPanel.add(cStreetTextField, gridBagConstraints);

        cNrLabel.setText("Numer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        companyAdressPanel.add(cNrLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        companyAdressPanel.add(cNrTextField, gridBagConstraints);

        cXLabel.setText("Położenie X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        companyAdressPanel.add(cXLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        companyAdressPanel.add(cXTextField, gridBagConstraints);

        cYLabel.setText("Położenie Y");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        companyAdressPanel.add(cYLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        companyAdressPanel.add(cYTextField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        specialPanel.add(companyAdressPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        customerPanel.add(specialPanel, gridBagConstraints);

        orderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Zamówienia"));
        orderPanel.setLayout(new java.awt.GridBagLayout());

        addOrderButton.setText("Dodaj zamówienie");
        addOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        orderPanel.add(addOrderButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        customerPanel.add(orderPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(customerPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        restauracja.dodajLosowegoKlienta();
        int selectedIndex = customerTable.getRowCount() - 1;
        ((CustomerTableModel) customerTable.getModel()).fireTableDataChanged();
        customerTable.getSelectionModel().setSelectionInterval(selectedIndex, selectedIndex);
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int selectionIndex = customerTable.getSelectionModel().getMinSelectionIndex();

        if (selectionIndex >= 0) {
            CustomerTableModel tableModel = (CustomerTableModel) customerTable.getModel();
            int selectedId = tableModel.getSelectedId();
            restauracja.usunKlienta(selectedId);
            ((CustomerTableModel) customerTable.getModel()).fireTableDataChanged();
            int lastIndex = customerTable.getRowCount() - 1;
            customerTable.getSelectionModel().setSelectionInterval(lastIndex, lastIndex);
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed

        int selectionIndex = customerTable.getSelectionModel().getMinSelectionIndex();
        CustomerTableModel tableModel = (CustomerTableModel) customerTable.getModel();
        int selectedId = tableModel.getSelectedId();
        Klient selectedKlient = mapaKlientow.get(selectedId);

        selectedKlient.setImie(firstNameTextField.getText());

        selectedKlient.setNazwisko(nameTextField.getText());

        selectedKlient.setNumerTelefonu(Integer.parseInt(telephoneTextField.getText()));

        selectedKlient.setEmail(emailTextField.getText());

        Adres adres = new Adres(streetTextField.getText(), Integer.parseInt(nrTextField.getText()), Integer.parseInt(xTextField.getText()), Integer.parseInt(yTextField.getText()));
        selectedKlient.setAdres(adres);

        if (selectedKlient.getRodzaj() == RodzajeKlientow.OKAZJONALNY) {

            ((Okazjonalny) selectedKlient).setKod(Integer.parseInt(codeTextField.getText()));

        } else if (selectedKlient.getRodzaj() == RodzajeKlientow.STALY) {

            ((Staly) selectedKlient).setZnizka(Integer.parseInt(discountTextField.getText()));
            ((Staly) selectedKlient).setPunktyLojalnosciowe(Integer.parseInt(pointsTextField.getText()));

        } else if (selectedKlient.getRodzaj() == RodzajeKlientow.FIRMOWY) {

            ((Firmowy) selectedKlient).setNumerKonta(Integer.parseInt(accountNumberTextField.getText()));
            ((Firmowy) selectedKlient).setRegon(Integer.parseInt(regonTextField.getText()));
            Adres adresKorespondencyjny = new Adres(cStreetTextField.getText(), Integer.parseInt(cNrTextField.getText()), Integer.parseInt(cXTextField.getText()), Integer.parseInt(cYTextField.getText()));
            ((Firmowy) selectedKlient).setAdresKorespond(adresKorespondencyjny);

        }

        Klient nowyKlient = null;
        if ((selectedKlient.getRodzaj().ordinal() - 1) != typeComboBox.getSelectedIndex()) {

            if (typeComboBox.getSelectedIndex() == 0) {
                nowyKlient = new Okazjonalny();
            } else if (typeComboBox.getSelectedIndex() == 1) {
                nowyKlient = new Staly();
            } else if (typeComboBox.getSelectedIndex() == 2) {
                nowyKlient = new Firmowy();

            }

            nowyKlient.setImie(selectedKlient.getImie());
            nowyKlient.setNazwisko(selectedKlient.getNazwisko());
            nowyKlient.setAdres(selectedKlient.getAdres());
            nowyKlient.setEmail(selectedKlient.getEmail());
            nowyKlient.setNumerTelefonu(selectedKlient.getNumerTelefonu());

            listaKlientow.add(listaKlientow.indexOf(selectedKlient), nowyKlient);
            listaKlientow.remove(selectedKlient);
            mapaKlientow.put(nowyKlient.getID(), nowyKlient);
            mapaKlientow.remove(selectedKlient.getId());

        }

        ((CustomerTableModel) customerTable.getModel()).fireTableDataChanged();
        customerTable.getSelectionModel().setSelectionInterval(selectionIndex, selectionIndex);
    }//GEN-LAST:event_changeButtonActionPerformed

    private void addOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButtonActionPerformed
        
        CustomerTableModel tableModel = (CustomerTableModel) customerTable.getModel();
        int selectionIndexCustomer = customerTable.getSelectionModel().getMinSelectionIndex();
        int selectedId = tableModel.getSelectedId();
        Klient klient = mapaKlientow.get(selectedId);
        Zamowienie zamowienie = klient.zamow();
        restauracja.obsluzZamowienie(zamowienie);
        ((CustomerTableModel) customerTable.getModel()).fireTableDataChanged();
        customerTable.getSelectionModel().setSelectionInterval(selectionIndexCustomer, selectionIndexCustomer);
        
    }//GEN-LAST:event_addOrderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerDialog dialog = new CustomerDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumberLabel;
    private javax.swing.JTextField accountNumberTextField;
    private javax.swing.JButton addButton;
    private javax.swing.JButton addOrderButton;
    private javax.swing.JPanel adressPanel;
    private javax.swing.JLabel cNrLabel;
    private javax.swing.JTextField cNrTextField;
    private javax.swing.JLabel cStreetLabel;
    private javax.swing.JTextField cStreetTextField;
    private javax.swing.JLabel cXLabel;
    private javax.swing.JTextField cXTextField;
    private javax.swing.JLabel cYLabel;
    private javax.swing.JTextField cYTextField;
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JTextField codeTextField;
    private javax.swing.JPanel companyAdressPanel;
    private javax.swing.JPanel customerPanel;
    private javax.swing.JTable customerTable;
    private javax.swing.JScrollPane customerTableScrollPane;
    private javax.swing.JLabel discountLabel;
    private javax.swing.JTextField discountTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nrLabel;
    private javax.swing.JTextField nrTextField;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JTextField pointsTextField;
    private javax.swing.JLabel regonLabel;
    private javax.swing.JTextField regonTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JPanel specialPanel;
    private javax.swing.JLabel streetLabel;
    private javax.swing.JTextField streetTextField;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JPanel toolbarPanel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel xLabel;
    private javax.swing.JTextField xTextField;
    private javax.swing.JLabel yLabel;
    private javax.swing.JTextField yTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * Ustawianie wartości pól CustomerDialogu oraz ustawienie TableModelu dla Tabeli klientów
     * (ukrywana jest kolumna z ID klienta)
     * @param restauracja
     */
    public void setDataModel(Restauracja restauracja) {
        this.restauracja = restauracja;
        this.listaKlientow = restauracja.getListaKlientow();
        this.mapaKlientow = restauracja.getMapaKlientow();
        customerTable.setModel(new CustomerTableModel(listaKlientow));
        customerTable.removeColumn(customerTable.getColumnModel().getColumn(CustomerColumns.ID.ordinal()));
    }

    /**
     * Definicja TableModelu dla Tabeli klientów.
     * Przesłanianie metod z klasy nadrzędnej
     */
    class CustomerTableModel extends AbstractTableModel {

        private final List<Klient> listaKlientow;

        public CustomerTableModel(List<Klient> listaKlientow) {
            this.listaKlientow = listaKlientow;
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {

        }

        @Override
        public String getColumnName(int column) {
            String columnName = "";
            if (null != CustomerColumns.values()[column]) {
                switch (CustomerColumns.values()[column]) {
                    case ID:
                        columnName = "Id";
                        break;
                    case FIRSTNAME:
                        columnName = "Imię";
                        break;
                    case NAME:
                        columnName = "Nazwisko";
                        break;
                    case TYPE:
                        columnName = "Rodzaj";
                        break;
                    default:
                        break;
                }
            }
            return columnName;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (CustomerColumns.values()[columnIndex] == CustomerColumns.ID) {
                return Integer.class;
            } else {
                return String.class;
            }
        }

        @Override
        public int getColumnCount() {
            return CustomerColumns.values().length;
        }

        @Override
        public int getRowCount() {
            return listaKlientow.size();
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Object result = null;
            Klient klient = listaKlientow.get(rowIndex);
            if (null != CustomerColumns.values()[columnIndex]) {
                switch (CustomerColumns.values()[columnIndex]) {
                    case ID:
                        result = klient.getID();
                        break;
                    case FIRSTNAME:
                        result = klient.getImie();
                        break;
                    case NAME:
                        result = klient.getNazwisko();
                        break;
                    case TYPE:
                        result = klient.getRodzaj().toString();
                        break;
                    default:
                        break;
                }
            }
            return result;
        }

        public int getSelectedId() {
            return (Integer) getValueAt(customerTable.getSelectedRow(), CustomerColumns.ID.ordinal());
        }

    }

    /**
     * Uzupelnianie szczegółowych informacji o kliencie na podstawie wyboru dokonanego w tabeli.
     */
    private void selectCustomer() {

        int selectionIndex = customerTable.getSelectionModel().getMinSelectionIndex();

        if (selectionIndex >= 0) {

            CustomerTableModel tableModel = (CustomerTableModel) customerTable.getModel();
            int selectedId = tableModel.getSelectedId();
            Klient selectedKlient = mapaKlientow.get(selectedId);

            typeComboBox.setSelectedIndex(0);
            typeComboBox.setSelectedIndex(selectedKlient.getRodzaj().ordinal() - 1);

            firstNameTextField.setText(selectedKlient.getImie());

            nameTextField.setText(selectedKlient.getNazwisko());

            telephoneTextField.setText(Integer.toString(selectedKlient.getNumerTelefonu()));

            emailTextField.setText(selectedKlient.getEmail());

            streetTextField.setText(selectedKlient.getAdres().getUlica());
            nrTextField.setText(Integer.toString(selectedKlient.getAdres().getNumerDomu()));
            xTextField.setText(Integer.toString(selectedKlient.getAdres().getPozycjaX()));
            yTextField.setText(Integer.toString(selectedKlient.getAdres().getPozycjaY()));

            codeLabel.setVisible(false);
            codeTextField.setVisible(false);

            discountLabel.setVisible(false);
            discountTextField.setVisible(false);
            pointsLabel.setVisible(false);
            pointsTextField.setVisible(false);

            accountNumberLabel.setVisible(false);
            accountNumberTextField.setVisible(false);
            regonLabel.setVisible(false);
            regonTextField.setVisible(false);
            companyAdressPanel.setVisible(false);

            if (selectedKlient.getRodzaj() == RodzajeKlientow.OKAZJONALNY) {

                codeLabel.setVisible(true);
                codeTextField.setVisible(true);
                codeTextField.setText(Integer.toString(((Okazjonalny) selectedKlient).getKod()));

            } else if (selectedKlient.getRodzaj() == RodzajeKlientow.STALY) {

                discountLabel.setVisible(true);
                discountTextField.setVisible(true);
                discountTextField.setText(Integer.toString(((Staly) selectedKlient).getZnizka()));

                pointsLabel.setVisible(true);
                pointsTextField.setVisible(true);
                pointsTextField.setText(Integer.toString(((Staly) selectedKlient).getPunktyLojalnosciowe()));

            } else if (selectedKlient.getRodzaj() == RodzajeKlientow.FIRMOWY) {

                accountNumberLabel.setVisible(true);
                accountNumberTextField.setVisible(true);
                accountNumberTextField.setText(Integer.toString(((Firmowy) selectedKlient).getNumerKonta()));

                regonLabel.setVisible(true);
                regonTextField.setVisible(true);
                regonTextField.setText(Integer.toString(((Firmowy) selectedKlient).getRegon()));

                companyAdressPanel.setVisible(true);
                cStreetTextField.setText(((Firmowy) selectedKlient).getAdresKorespond().getUlica());
                cNrTextField.setText(Integer.toString(((Firmowy) selectedKlient).getAdresKorespond().getNumerDomu()));
                cXTextField.setText(Integer.toString(((Firmowy) selectedKlient).getAdresKorespond().getPozycjaX()));
                cYTextField.setText(Integer.toString(((Firmowy) selectedKlient).getAdresKorespond().getPozycjaY()));

            }
            
        }

    }

}
