/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author akamojo
 */
public class DeliverDialog extends javax.swing.JDialog {

    private List<Dostawca> listaDostawcow;
    private Map<Integer, Dostawca> mapaDostawcow;
    private Restauracja restauracja;

    /**
     * Creates new form DeliverDialog
     */
    public DeliverDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolbarPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        deliverTableScrollPane = new javax.swing.JScrollPane();
        deliverTable = new javax.swing.JTable();
        deliverPanel = new javax.swing.JPanel();
        peselLabel = new javax.swing.JLabel();
        peselTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        licencePanel = new javax.swing.JPanel();
        carCheckBox = new javax.swing.JCheckBox();
        motorCheckBox = new javax.swing.JCheckBox();
        orderPanel = new javax.swing.JPanel();
        orderScrollPane = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dostawcy");
        setMinimumSize(new java.awt.Dimension(300, 500));
        setPreferredSize(new java.awt.Dimension(600, 800));

        toolbarPanel.setLayout(new java.awt.GridBagLayout());

        addButton.setText("Dodaj Dostawcę");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolbarPanel.add(addButton, gridBagConstraints);

        removeButton.setText("Usuń Dostawcę");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolbarPanel.add(removeButton, gridBagConstraints);

        changeButton.setText("Zmień Dostawcę");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toolbarPanel.add(changeButton, gridBagConstraints);

        getContentPane().add(toolbarPanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.setLayout(new java.awt.GridBagLayout());

        tablePanel.setLayout(new java.awt.GridBagLayout());

        deliverTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Pesel", "Imię", "Nazwisko"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        deliverTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        deliverTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if(!e.getValueIsAdjusting()){
                    selectDeliver();
                }
            }
        });
        deliverTableScrollPane.setViewportView(deliverTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        tablePanel.add(deliverTableScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(tablePanel, gridBagConstraints);

        deliverPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dostawca"));
        deliverPanel.setLayout(new java.awt.GridBagLayout());

        peselLabel.setText("Pesel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        deliverPanel.add(peselLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        deliverPanel.add(peselTextField, gridBagConstraints);

        firstNameLabel.setText("Imię");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        deliverPanel.add(firstNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        deliverPanel.add(firstNameTextField, gridBagConstraints);

        nameLabel.setText("Nazwisko");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        deliverPanel.add(nameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 5, 5);
        deliverPanel.add(nameTextField, gridBagConstraints);

        licencePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Prawo Jazdy"));
        licencePanel.setLayout(new java.awt.GridBagLayout());

        carCheckBox.setText("Samochód");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        licencePanel.add(carCheckBox, gridBagConstraints);

        motorCheckBox.setText("Skuter");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        licencePanel.add(motorCheckBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliverPanel.add(licencePanel, gridBagConstraints);

        orderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Zamówienia"));
        orderPanel.setLayout(new java.awt.GridBagLayout());

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numer", "Koszt", "Status", "Dostawca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderScrollPane.setViewportView(orderTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        orderPanel.add(orderScrollPane, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        deliverPanel.add(orderPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(deliverPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        
        int selectionIndex = deliverTable.getSelectionModel().getMinSelectionIndex();
        DeliverTableModel tableModel = (DeliverTableModel) deliverTable.getModel();
        int selectedId = tableModel.getSelectedId();
        Dostawca selectedDostawca = mapaDostawcow.get(selectedId);
        selectedDostawca.setPesel(Integer.parseInt(peselTextField.getText()));
        selectedDostawca.setImie(firstNameTextField.getText());
        selectedDostawca.setNazwisko(nameTextField.getText());
        Set<PrawoJazdy> selectedListaPrawaJazdy = new HashSet<PrawoJazdy>();
        if (carCheckBox.isSelected()) {
            selectedListaPrawaJazdy.add(PrawoJazdy.SAMOCHOD);
        }
        if (motorCheckBox.isSelected()) {
            selectedListaPrawaJazdy.add(PrawoJazdy.SKUTER);
        }
        selectedDostawca.setListaPrawaJazdy(selectedListaPrawaJazdy);
        ((DeliverTableModel) deliverTable.getModel()).fireTableDataChanged();
        deliverTable.getSelectionModel().setSelectionInterval(selectionIndex, selectionIndex);
        
    }//GEN-LAST:event_changeButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        
        restauracja.dodajLosowegoDostawce();
        int selectedIndex = deliverTable.getRowCount() - 1;
        ((DeliverTableModel) deliverTable.getModel()).fireTableDataChanged();
        deliverTable.getSelectionModel().setSelectionInterval(selectedIndex, selectedIndex);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        
        int selectionIndex = deliverTable.getSelectionModel().getMinSelectionIndex();
        if (selectionIndex >= 0) {
            DeliverTableModel tableModel = (DeliverTableModel) deliverTable.getModel();
            int selectedId = tableModel.getSelectedId();
            restauracja.usunDostawce(selectedId);
            ((DeliverTableModel) deliverTable.getModel()).fireTableDataChanged();
            int lastIndex = deliverTable.getRowCount() - 1;
            deliverTable.getSelectionModel().setSelectionInterval(lastIndex, lastIndex);
        }
        
    }//GEN-LAST:event_removeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliverDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliverDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliverDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliverDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DeliverDialog dialog = new DeliverDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JCheckBox carCheckBox;
    private javax.swing.JButton changeButton;
    private javax.swing.JPanel deliverPanel;
    private javax.swing.JTable deliverTable;
    private javax.swing.JScrollPane deliverTableScrollPane;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JPanel licencePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JCheckBox motorCheckBox;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JScrollPane orderScrollPane;
    private javax.swing.JTable orderTable;
    private javax.swing.JLabel peselLabel;
    private javax.swing.JTextField peselTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Ustawianie wartości pól DeliverDialogu oraz TableModelu dla tabeli dostawców
     * @param restauracja
     */
    public void setDataModel(Restauracja restauracja) {
        this.restauracja = restauracja;
        this.mapaDostawcow = restauracja.getMapaDostawcow();
        this.listaDostawcow = restauracja.getListaDostawcow();
        deliverTable.setModel(new DeliverTableModel(listaDostawcow));
        deliverTable.removeColumn(deliverTable.getColumnModel().getColumn(DeliverColumns.ID.ordinal()));
    }

    /**
     * Definicja TableModelu dla tabeli dostawców i przesłanianie metod
     * (Dziedziczącego z AbstractTableModel)
     */
    class DeliverTableModel extends AbstractTableModel {

        private final List<Dostawca> listaDostawcow;

        public DeliverTableModel(List<Dostawca> listaDostawcow) {
            this.listaDostawcow = listaDostawcow;
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {

        }

        @Override
        public String getColumnName(int column) {
            String columnName = "";
            if (null != DeliverColumns.values()[column]) {
                switch (DeliverColumns.values()[column]) {
                    case ID:
                        columnName = "Id";
                        break;
                    case PESEL:
                        columnName = "Pesel";
                        break;
                    case FIRSTNAME:
                        columnName = "Imię";
                        break;
                    case NAME:
                        columnName = "Nazwisko";
                        break;
                    default:
                        break;
                }
            }
            return columnName;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (DeliverColumns.values()[columnIndex] == DeliverColumns.ID || DeliverColumns.values()[columnIndex] == DeliverColumns.PESEL) {
                return Integer.class;
            } else {
                return String.class;
            }
        }

        @Override
        public int getColumnCount() {
            return DeliverColumns.values().length;
        }

        @Override
        public int getRowCount() {
            return listaDostawcow.size();
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Object result = null;
            Dostawca dostawca = listaDostawcow.get(rowIndex);
            if (null != DeliverColumns.values()[columnIndex]) {
                switch (DeliverColumns.values()[columnIndex]) {
                    case ID:
                        result = dostawca.getID();
                        break;
                    case PESEL:
                        result = dostawca.getPesel();
                        break;
                    case FIRSTNAME:
                        result = dostawca.getImie();
                        break;
                    case NAME:
                        result = dostawca.getNazwisko();
                        break;
                    default:
                        break;
                }
            }
            return result;
        }

        public int getSelectedId() {
            return (Integer) getValueAt(deliverTable.getSelectedRow(), DeliverColumns.ID.ordinal());
        }

    }

    /**
     * Uzupełnianie szczegółowych informacji o dostawcy na podstawie wyboru dokonanego w tabeli
     */
    private void selectDeliver() {

        int selectionIndex = deliverTable.getSelectionModel().getMinSelectionIndex();

        if (selectionIndex >= 0) {

            DeliverTableModel tableModel = (DeliverTableModel) deliverTable.getModel();
            int selectedId = tableModel.getSelectedId();
            Dostawca selectedDostawca = mapaDostawcow.get(selectedId);
            peselTextField.setText(Integer.toString(selectedDostawca.getPesel()));
            firstNameTextField.setText(selectedDostawca.getImie());
            nameTextField.setText(selectedDostawca.getNazwisko());
            carCheckBox.setSelected(false);
            motorCheckBox.setSelected(false);

            for (PrawoJazdy i : selectedDostawca.getListaPrawaJazdy()) {
                if (i == PrawoJazdy.SAMOCHOD) {
                    carCheckBox.setSelected(true);
                } else if (i == PrawoJazdy.SKUTER) {
                    motorCheckBox.setSelected(true);
                }
            }
            
            orderTable.removeAll();
            orderTable.setModel(new OrderTableModel(selectedDostawca.getListaZamowien()));

        }

    }

    /**
     * Definicja TableModelu dla tabeli zamówień (innej dla każdego dostawcy)
     */
    class OrderTableModel extends AbstractTableModel {

        private final List<Zamowienie> listaZamowien;

        public OrderTableModel(List<Zamowienie> listaZamowien) {
            this.listaZamowien = listaZamowien;
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {

        }

        @Override
        public String getColumnName(int column) {
            String columnName = "";
            if (null != OrderColumns.values()[column]) {
                switch (OrderColumns.values()[column]) {
                    case NUMER:
                        columnName = "Numer";
                        break;
                    case KOSZT:
                        columnName = "Koszt";
                        break;
                    case STATUS:
                        columnName = "Status";
                        break;
                    case KLIENT:
                        columnName = "Dostawca";
                        break;
                    default:
                        break;
                }
            }
            return columnName;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (OrderColumns.values()[columnIndex] == OrderColumns.NUMER) {
                return Integer.class;
            } else if (OrderColumns.values()[columnIndex] == OrderColumns.KOSZT) {
                return Float.class;
            } else {
                return String.class;
            }
        }

        @Override
        public int getColumnCount() {
            return OrderColumns.values().length;
        }

        @Override
        public int getRowCount() {
            return listaZamowien.size();
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Object result = null;
            Zamowienie zamowienie = listaZamowien.get(rowIndex);
            if (null != OrderColumns.values()[columnIndex]) {
                switch (OrderColumns.values()[columnIndex]) {
                    case NUMER:
                        result = zamowienie.getNumer();
                        break;
                    case STATUS:
                        result = zamowienie.getStatus().toString();
                        break;
                    case KOSZT:
                        result = zamowienie.getKoszt();
                        break;
                    case KLIENT:
                    	int idDostawcy = zamowienie.getIdDostawcy();
                        if (idDostawcy == 0) {
                            result = "Nie przydzielono";
                        } else {
                        	Dostawca dostawca = mapaDostawcow.get(idDostawcy);
                            result = dostawca.getImie() + " " + dostawca.getNazwisko();
                        }
                        break;
                    default:
                        break;
                }
            }
            return result;
        }

        public int getSelectedNr() {
            return (Integer) getValueAt(orderTable.getSelectedRow(), OrderColumns.NUMER.ordinal());
        }

    }
    

}
