/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

import java.awt.Color;
import java.awt.Component;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author akamojo
 */
public class InfoJFrame extends javax.swing.JFrame implements OrdersListener {

    private Restauracja restauracja;
    private List<Zamowienie> listaZamowien;
    private Mapa mapa;
    private OrderTableModel ordersModel;

    /**
     * Creates new form InfoJFrame
     */
    public InfoJFrame() {
        try {
            initComponents();
            initModel();
            this.mapa = new Mapa(this);
            mapa.setSize(mainSplitPane.getSize().width, mainSplitPane.getSize().height);
            mapa.setLocation(0, 0);
            mainSplitPane.setRightComponent(mapa);
        } catch (IOException ex) {
            Logger.getLogger(InfoJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        navigationPanel = new javax.swing.JPanel();
        restaurantButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        customersButton = new javax.swing.JButton();
        deliversButton = new javax.swing.JButton();
        savePanel = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        mainSplitPane = new javax.swing.JSplitPane();
        ordersPanel = new javax.swing.JPanel();
        ordersScrollPane = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        infoPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza");
        setPreferredSize(new java.awt.Dimension(1200, 600));

        navigationPanel.setLayout(new java.awt.GridBagLayout());

        restaurantButton.setText("Restauracja");
        restaurantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaurantButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        navigationPanel.add(restaurantButton, gridBagConstraints);

        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        navigationPanel.add(menuButton, gridBagConstraints);

        customersButton.setText("Klienci");
        customersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        navigationPanel.add(customersButton, gridBagConstraints);

        deliversButton.setText("Dostawcy");
        deliversButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliversButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        navigationPanel.add(deliversButton, gridBagConstraints);

        getContentPane().add(navigationPanel, java.awt.BorderLayout.NORTH);

        saveButton.setText("Zawróć wszystkich dostawców do restauracji i zapisz stan");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        savePanel.add(saveButton);

        getContentPane().add(savePanel, java.awt.BorderLayout.PAGE_END);

        mainPanel.setLayout(new java.awt.GridBagLayout());

        mainSplitPane.setDividerLocation(350);
        mainSplitPane.setDividerSize(10);
        mainSplitPane.setResizeWeight(0.5);
        mainSplitPane.setToolTipText("");
        mainSplitPane.setOneTouchExpandable(true);

        ordersPanel.setLayout(new java.awt.GridBagLayout());

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ordersScrollPane.setViewportView(ordersTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        ordersPanel.add(ordersScrollPane, gridBagConstraints);

        mainSplitPane.setLeftComponent(ordersPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        mainPanel.add(mainSplitPane, gridBagConstraints);

        infoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel Informacyjny"));
        infoPanel.add(infoLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        mainPanel.add(infoPanel, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
        CustomerDialog customer = new CustomerDialog(this, rootPaneCheckingEnabled);
        customer.setDataModel(restauracja);
        customer.setLocation(Pizza.getShowPosition(customer));
        customer.setVisible(true);
    }//GEN-LAST:event_customersButtonActionPerformed

    private void deliversButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliversButtonActionPerformed
        DeliverDialog deliver = new DeliverDialog(this, rootPaneCheckingEnabled);
        deliver.setDataModel(restauracja);
        deliver.setLocation(Pizza.getShowPosition(deliver));
        deliver.setVisible(true);
    }//GEN-LAST:event_deliversButtonActionPerformed

    private void restaurantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaurantButtonActionPerformed
        RestaurantDialog restaurant = new RestaurantDialog(this, rootPaneCheckingEnabled);
        restaurant.setDataModel(restauracja);
        restaurant.setLocation(Pizza.getShowPosition(restaurant));
        restaurant.setVisible(true);
    }//GEN-LAST:event_restaurantButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        MenuDialog menu = new MenuDialog(this, rootPaneCheckingEnabled);
        menu.setLocation(Pizza.getShowPosition(menu));
        menu.setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        FileOutputStream fout = null;
        try {
            for (Klient i : restauracja.getListaKlientow()) {
                try {
                    i.interrupt();
                } catch (Exception ex) {
                    //nothing to do
                }
            }
            for (Dostawca i : restauracja.getListaDostawcow()) {
                if (i.getStatus() == Status.TRASA) {
                    i.getPojazd().setStatus(Status.DOSTEPNY);
                    i.setStatus(Status.DOSTEPNY);
                    i.setDestination(restauracja.getAdres());
                    i.setX(restauracja.getAdres().getPozycjaX());
                    i.setY(restauracja.getAdres().getPozycjaY());
                    i.setListaZamowien(new ArrayList<Zamowienie>());
                    try {
                        i.interrupt();
                    } catch (Exception ex) {
                        //nothing to do
                    }
                }
            }
            for (Zamowienie i : restauracja.getListaZamowien()) {
                if (i.getStatus() == StatusZamowienia.REALIZOWANE || i.getStatus() == StatusZamowienia.PRZYDZIELONE || i.getStatus() == StatusZamowienia.PRZYGOTOWYWANE) {
                    i.setStatus(StatusZamowienia.OCZEKUJACE);
                }
            }

            fout = new FileOutputStream("data.txt", true);
            ObjectOutputStream oos = new ObjectOutputStream(fout);
            oos.writeObject(restauracja);
            oos.flush();
            oos.close();
            System.exit(0);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(InfoJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(InfoJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fout.close();
            } catch (IOException ex) {
                Logger.getLogger(InfoJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException,
            IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InfoJFrame info = new InfoJFrame();
                info.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customersButton;
    private javax.swing.JButton deliversButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JSplitPane mainSplitPane;
    private javax.swing.JButton menuButton;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JScrollPane ordersScrollPane;
    private javax.swing.JTable ordersTable;
    private javax.swing.JButton restaurantButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel savePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Ustawianie wartości pól JFrame'a. Wywołanie metody wczytującej z pliku.
     * Restauracja jest Singletonem, jest tylko jedno jest wystąpienie (aby
     * można było łatwo się do niej dostać z każdej klasy). Ustalenie modelu dla
     * ogólnej tabeli zamówień oraz Renderera dla kolorowania wierszy.
     */
    private void initModel() {
        Restauracja.initFromFile();
        restauracja = Restauracja.getInstance();
        this.restauracja = restauracja;
        restauracja.addOrdersListener(this);
        restauracja.start();
        this.listaZamowien = restauracja.getListaZamowien();
        ordersModel = new OrderTableModel(listaZamowien);
        ordersTable.setModel(ordersModel);
        OrderRenderer renderer = new OrderRenderer();
        TableColumn column = ordersTable.getColumnModel().getColumn(OrdersColumns.NUMER.ordinal());
        column.setCellRenderer(renderer);
        column = ordersTable.getColumnModel().getColumn(OrdersColumns.STATUS.ordinal());
        column.setCellRenderer(renderer);
        column = ordersTable.getColumnModel().getColumn(OrdersColumns.KOSZT.ordinal());
        column.setCellRenderer(renderer);
        column = ordersTable.getColumnModel().getColumn(OrdersColumns.KLIENT.ordinal());
        column.setCellRenderer(renderer);
        column = ordersTable.getColumnModel().getColumn(OrdersColumns.DOSTAWCA.ordinal());
        column.setCellRenderer(renderer);
    }

    /**
     * Metoda zwraca mapę.
     *
     * @return
     */
    public Mapa getMapa() {
        return mapa;
    }

    /**
     * Metoda ustawia mapę.
     *
     * @param mapa
     */
    public void setMapa(Mapa mapa) {
        this.mapa = mapa;
    }

    /**
     * Ustawienie tekstu wyświetlającego się w panelu informacyjnym. Znajdują
     * się tu informacje o obiekcie, który został wybrany przez użytkownika
     * poprzez kliknięcie myszką.
     *
     * @param info
     */
    public void setInfoMessage(String info) {
        infoLabel.setText(info);
    }

    /**
     * Klasa definiująca TableModel dla ogólnej tabeli zamówień.
     */
    class OrderTableModel extends AbstractTableModel {

        private final List<Zamowienie> listaZamowien;

        public OrderTableModel(List<Zamowienie> listaZamowien) {
            this.listaZamowien = listaZamowien;
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {

        }

        @Override
        public String getColumnName(int column) {
            String columnName = "";
            if (null != OrdersColumns.values()[column]) {
                switch (OrdersColumns.values()[column]) {
                    case NUMER:
                        columnName = "Numer";
                        break;
                    case KOSZT:
                        columnName = "Koszt";
                        break;
                    case STATUS:
                        columnName = "Status";
                        break;
                    case KLIENT:
                        columnName = "Klient";
                        break;
                    case DOSTAWCA:
                        columnName = "Dostawca";
                        break;
                    default:
                        break;
                }
            }
            return columnName;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (OrdersColumns.values()[columnIndex] == OrdersColumns.NUMER) {
                return Integer.class;
            } else if (OrdersColumns.values()[columnIndex] == OrdersColumns.KOSZT) {
                return Float.class;
            } else {
                return String.class;
            }
        }

        @Override
        public int getColumnCount() {
            return OrdersColumns.values().length;
        }

        @Override
        public int getRowCount() {
            return listaZamowien.size();
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Object result = null;
            Zamowienie zamowienie = listaZamowien.get(rowIndex);
            if (null != OrdersColumns.values()[columnIndex]) {
                switch (OrdersColumns.values()[columnIndex]) {
                    case NUMER:
                        result = zamowienie.getNumer();
                        break;
                    case STATUS:
                        result = zamowienie.getStatus();
                        break;
                    case KOSZT:
                        result = zamowienie.getKoszt();
                        break;
                    case KLIENT:
                        int idKlienta = zamowienie.getIdKlienta();
                        if (idKlienta == 0) {
                            result = "Nie przydzielono";
                        } else {
                            Klient klient = Restauracja.getInstance().getMapaKlientow().get(idKlienta);
                            result = klient.getImie() + " " + klient.getNazwisko();
                        }
                        break;
                    case DOSTAWCA:
                        int idDostawcy = zamowienie.getIdDostawcy();
                        if (idDostawcy == 0) {
                            result = "Nie przydzielono";
                        } else {
                            Dostawca dostawca = Restauracja.getInstance().getMapaDostawcow().get(idDostawcy);
                            result = dostawca.getImie() + " " + dostawca.getNazwisko();
                        }
                        break;
                    default:
                        break;
                }
            }
            return result;
        }

        public int getSelectedNr() {
            return (Integer) getValueAt(ordersTable.getSelectedRow(), OrdersColumns.NUMER.ordinal());
        }

    }

    /**
     * Metoda odświeżająca dane znajdujące się w tabeli zamówień.
     */
    @Override
    public void ordersChanged() {
        ordersModel.fireTableDataChanged();
    }

    /**
     * Renderer do kolorowania wierszy w zależności od statusu zamówienia.
     */
    class OrderRenderer extends DefaultTableCellRenderer {

        private static final long serialVersionUID = 1L;

        public OrderRenderer() {
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            Component renderer = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            StatusZamowienia status = (StatusZamowienia) ordersModel.getValueAt(row, OrdersColumns.STATUS.ordinal());
            if (status == StatusZamowienia.ZREALIZOWANE) {
                renderer.setForeground(Color.GRAY);
            } else if (status == StatusZamowienia.PRZYDZIELONE) {
                renderer.setForeground(Color.GREEN);
            } else {
                renderer.setForeground(Color.BLACK);
            }
            return renderer;
        }
    }

}
