/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

import java.util.List;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author akamojo
 */
public class MenuDialog extends javax.swing.JDialog {

    private List<Posilek> listaPosilkow;

    /**
     * Creates new form MenuJDialog
     */
    public MenuDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaPosilkow = Restauracja.getInstance().getListaPosilkow();
        menuTable.setModel(new MenuTableModel(listaPosilkow));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        menuLabel = new javax.swing.JLabel();
        addMealButton = new javax.swing.JButton();
        menuScrollPane = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        menuLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        menuLabel.setText("Menu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(menuLabel, gridBagConstraints);

        addMealButton.setText("Dodaj losowy posiłek");
        addMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMealButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(addMealButton, gridBagConstraints);

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nazwa", "Cena", "Kategoria", "Rozmiar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        menuScrollPane.setViewportView(menuTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(menuScrollPane, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMealButtonActionPerformed
        Restauracja.getInstance().dodajLosowyPosilek();
        int selectedIndex = menuTable.getRowCount() - 1;
        ((MenuTableModel) menuTable.getModel()).fireTableDataChanged();
        menuTable.getSelectionModel().setSelectionInterval(selectedIndex, selectedIndex);
    }//GEN-LAST:event_addMealButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuDialog dialog = new MenuDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMealButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JScrollPane menuScrollPane;
    private javax.swing.JTable menuTable;
    // End of variables declaration//GEN-END:variables

    /**
     * Klasa definiująca TableModel dla menu
     */
    class MenuTableModel extends AbstractTableModel {

        private final List<Posilek> listaPosilkow;
        
        public MenuTableModel(List<Posilek> listaPosilkow) {
            this.listaPosilkow = listaPosilkow;
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {

        }

        @Override
        public String getColumnName(int column) {
            String columnName = "";
            if (null != MenuColumns.values()[column]) {
                switch (MenuColumns.values()[column]) {
                    case NAZWA:
                        columnName = "Nazwa";
                        break;
                    case KOSZT:
                        columnName = "Koszt";
                        break;
                    case KATEGORIA:
                        columnName = "Kategoria";
                        break;
                    case ROZMIAR:
                        columnName = "Rozmiar";
                        break;
                    default:
                        break;
                }
            }
            return columnName;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            if (MenuColumns.values()[columnIndex] == MenuColumns.KOSZT) {
                return Float.class;
            } else {
                return String.class;
            }
        }

        @Override
        public int getColumnCount() {
            return MenuColumns.values().length;
        }

        @Override
        public int getRowCount() {
            return listaPosilkow.size();
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Object result = null;
            Posilek posilek = listaPosilkow.get(rowIndex);
            if (null != MenuColumns.values()[columnIndex]) {
                switch (MenuColumns.values()[columnIndex]) {
                    case NAZWA:
                        result = posilek.getNazwa();
                        break;
                    case KATEGORIA:
                        result = posilek.getKategoria().toString();
                        break;
                    case KOSZT:
                        result = posilek.getCena();
                        break;
                    case ROZMIAR:
                        result = posilek.getRozmiar().toString();
                        break;
                    default:
                        break;
                }
            }
            return result;
        }

        public int getSelectedNr() {
            return (Integer) getValueAt(menuTable.getSelectedRow(), MenuColumns.NAZWA.ordinal());
        }

    }
}
